### ISSUE TITLE
CLI "help"  strings

### ISSUE THREAD

**Issue by delgadom** [ClimateImpactLab/DataFS#115]
I think they can be written using a conventional docstring. Anyhow, there is barely anything there and we need to give the user some help from the command line.

Also, the CLI is not currently documented in the API. click doesn't have a sphinx extension as far as I can tell, so I think we'll have to create this documentation manually.

**Comment by jgerardsimcock** [comment]
Ok. I think this is important. I'll work on getting this done by the end of week.

**Comment by delgadom** [comment]
Closed by #149
