### ISSUE TITLE
Add Documentation for tagging and naming conventions

### ISSUE THREAD

**Issue by jgerardsimcock** [ClimateImpactLab/DataFS#162]
Currently we provide no guidance on how to name or tag archives for easy retrieval. We'll need this soon as new users come online.

**Comment by delgadom** [comment]
Tagging provided in #173, could still use more documentation on naming/searching best practices. We should also have more documentation on impactlab-specific naming conventions... see ClimateImpactLab/impactlab_user#35

I'm moving this issue to milestone 0.6.10

**Comment by delgadom** [comment]
@jgerardsimcock did you complete this? If so, feel free to close.
