### ISSUE TITLE
Naming convention enforcement

### ISSUE THREAD

**Issue by jgerardsimcock** [ClimateImpactLab/DataFS#168]
First pass attempt to characterize and describe potential implementation of enforcement of naming conventions. 

We're providing two types of name enforcement measures available to admins:
1. Required "top-level-domains" which are the first element in an archive's path
2. Regex pattern matching

If using TLD enforcement:
1. Enable enforcement of naming conventions on your archive names.
2. All archive names will be required to begin with '{tld}/'. This will mirror current CLI conventions

Proposed implementation

1. On `create_archive_table` the entries for `valid_top_level_domains` and `regex` will be added into the `{table_name}.spec` table in the manager. 

2. Add new method `set_top_level_domains` that allows an entry of `valid_top_level_domains` into spec config table. This will call `update_spec_config` with `document_name=valid_top_level_domains` and `spec` will be populated with an empty list. 

3. Add new method to `set_regex_pattern` for setting and getting archive_names into spec_config table. This will call `update_spec_config`  with  `document_name=regex_patterns`  and `spec` will be an empty string. 
 
4. If enforced, enforcement of TLD will happen on create_archive and archive_names will be checked against values in `valid_top_level_domains` doc as well . 
 
 5. If enforced, enforcement of archive_name against a `regex_pattern` matching will also happen on create_archive.

**Comment by delgadom** [comment]
Resolved in #173
