### ISSUE TITLE
remove DataArchive properties that rely on manager calls

### ISSUE THREAD

**Issue by delgadom** [ClimateImpactLab/DataFS#72]
The fact that these are properties is potentially confusing and could lead to unintended calls to the manager.

Propose changing the following properties into functions:

* `latest_version` --> `get_latest_version`
* `versions` --> `get_versions`
* `latest_hash` --> `get_latest_hash`
* `history` --> `get_history`
* `metadata` --> `get_metadata`

These changes would break tests and docs/examples which explicitly rely on these properties.

**Comment by jgerardsimcock** [comment]
merged in #74
