### ISSUE TITLE
Frequent BackUp of metadata table to S3 or other data store

### ISSUE THREAD

**Issue by jgerardsimcock** [ClimateImpactLab/DataFS#82]
There is currently no backup of metadata table to backup data store. If this thing gets deleted or goes down then all your work is lost. Possible solutions would give admin users the rights to backup tables at defined intervals as well as ad-hoc data backup

*recurring
```api.manager.backup_metadata_table(table_name='my_metadata_table', backup_location='s3', interval='hourly')```

*ad-hoc
```api.manager.backup_metadata_table(table_name='my_metadata_table', backup_location='s3')```

**Comment by delgadom** [comment]
I'd also be totally happy if this were just something you did from the AWS management console. An admin-facing method would be awesome though!

**Comment by delgadom** [comment]
This is an area of active development outside the DataFS project (nice going @jgerardsimcock!). While we may include support and/or documentation for this at some point in the future, I'm going to say this is out of scope for the time being.
